version: "3"

services:

  web:
    build:
      context: .
      dockerfile: compose/web/local/Dockerfile
    image: exchange_radar_web
    container_name: exchange-radar-web
    env_file:
      - ./.envs/.local/.web
    depends_on:
      - rabbitmq
    ports:
      - "9000:9000"
    volumes:
      - ./exchange_radar/web:/app/exchange_radar/web
    command: /start

  rabbitmq:
    image: rabbitmq:3.11.15-management-alpine
    container_name: exchange-radar-rabbitmq
    env_file:
      - ./.envs/.local/.rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:7.2-alpine
    container_name: exchange-radar-redis
    ports:
      - '6379:6379'

  producer-binance:
    build:
      context: .
      dockerfile: compose/producer/binance/Dockerfile
    image: exchange_radar_producer_binance
    container_name: exchange-radar-producer-binance
    env_file:
      - ./.envs/.local/.rabbitmq
      - ./.envs/.local/.producer
      - ./.envs/.local/.redis
    depends_on:
      - rabbitmq
    volumes:
      - ./exchange_radar/producer:/app/exchange_radar/producer
    command: /start

  producer-kucoin:
    build:
      context: .
      dockerfile: compose/producer/kucoin/Dockerfile
    image: exchange_radar_producer_kucoin
    container_name: exchange-radar-producer-kucoin
    env_file:
      - ./.envs/.local/.rabbitmq
      - ./.envs/.local/.producer
      - ./.envs/.local/.redis
    depends_on:
      - rabbitmq
    volumes:
      - ./exchange_radar/producer:/app/exchange_radar/producer
    command: /start

  producer-coinbase:
    build:
      context: .
      dockerfile: compose/producer/coinbase/Dockerfile
    image: exchange_radar_producer_coinbase
    container_name: exchange-radar-producer-coinbase
    env_file:
      - ./.envs/.local/.rabbitmq
      - ./.envs/.local/.producer
      - ./.envs/.local/.redis
    depends_on:
      - rabbitmq
    volumes:
      - ./exchange_radar/producer:/app/exchange_radar/producer
    command: /start

  producer-kraken:
    build:
      context: .
      dockerfile: compose/producer/kraken/Dockerfile
    image: exchange_radar_producer_kraken
    container_name: exchange-radar-producer-kraken
    env_file:
      - ./.envs/.local/.rabbitmq
      - ./.envs/.local/.producer
      - ./.envs/.local/.redis
    depends_on:
      - rabbitmq
    volumes:
      - ./exchange_radar/producer:/app/exchange_radar/producer
    command: /start

  consumer:
    build:
      context: .
      dockerfile: compose/consumer/Dockerfile
    image: exchange_radar_consumer
    env_file:
      - ./.envs/.local/.rabbitmq
      - ./.envs/.local/.consumer
    depends_on:
      - rabbitmq
    volumes:
      - ./exchange_radar/consumer:/app/exchange_radar/consumer
    command: /start

  tests:
    build:
      context: .
      dockerfile: compose/tests/Dockerfile
    image: exchange_radar_tests
    container_name: exchange-radar-tests
    env_file:
      - ./.envs/.local/.rabbitmq
      - ./.envs/.local/.producer
    volumes:
      - .:/app
    profiles:
      - donotstart
