#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

if [ -z "${WORKERS}" ]; then
  WORKERS="$((2 * $(getconf _NPROCESSORS_ONLN) + 1))";
fi
echo "Starting service web with $(($WORKERS)) worker(s)"

exec uvicorn exchange_radar.web.src.main:app \
--host 0.0.0.0 \
--port 9000 \
--workers $WORKERS \
--proxy-headers \
--forwarded-allow-ips="*" \
--no-access-log
