#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

rabbitmq_ready() {
python << END
import socket
import sys

import time

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

try:
    s.connect(("${RABBITMQ_HOST}", ${RABBITMQ_PORT}))
except socket.error as e:
    sys.exit(-1)

sys.exit(0)

END
}
until rabbitmq_ready; do
  >&2 echo 'Waiting for RabbitMQ to become available...'
  sleep 1
done
>&2 echo 'RabbitMQ is available'

exec "$@"
