# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI/CD

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v3

      - name: Run pre-commit
        uses: pre-commit/action@v2.0.3

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v3

      - name: Build the Stack
        run: docker-compose -f local.yml build tests

      - name: Run Django Tests
        run: docker-compose -f local.yml run tests coverage run -m pytest -v --tb=short -p no:warnings

      - name: Full Code Test Coverage Check (min. 95%)
        run: docker-compose -f local.yml run tests coverage report --fail-under=95

      - name: Tear down the Stack
        run:  docker-compose -f local.yml down
